parameters:
    locale: en

enhavo_app:
    template:
        base: 'base.html.twig'
    menu:
        dashboard:
            type: dashboard
        user:
            type: user_user
        group:
            type: user_group
        page:
            type: page
            label: Seiten
        article:
            type: article
        navigation:
            type: navigation
        template:
            type: template

enhavo_block:
    blocks:
        picture:
            type: picture
        gallery:
            type: gallery
        text:
            type: text
        text_picture:
            type: text_picture
        cite:
            type: cite
        video:
            type: video
        article_stream:
            type: article_stream
        one_column:
            type: one_column
        two_column:
            type: two_column
        three_column:
            type: three_column
        template:
            type: template

enhavo_theme:
    theme: theme